### ISSUE TITLE
MAPA MENTAL_ANTONIA MARTINEZ SANDOVAL

### ISSUE THREAD

**Issue by 2003lulu** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-2003lulu#1]
[MAPA MENTAL-web 3.0_ANTONIA MARTINEZ SANDOVAL.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-2003lulu/files/14593108/MAPA.MENTAL-web.3.0_ANTONIA.MARTINEZ.SANDOVAL.pdf)

**Comment by josealfredo79** [comment]
Falta la calificacion...

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
